blogdemo/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('',views.index,name='index'),     # 入口路由
    path('about/',views.about,name='about'), # about 视图
    path('post/<int:pk>',views.PostDetailView.as_view(),name='post_detail'), # 详情视图 使用DetailView 参数名必须取pk
    path('post/all/',views.PostListView.as_view(),name='post_list'),    # 文章列表
    path('post/tags/<str:tag>',views.getTag,name='tag_post_list'),       # 分类
    path('upfile/',views.upfile,name='upfile'),   # 上传文件
    path('savefile/',views.savefile,name='savefile'),   # 上传文件

    path('pdf/',views.showPdf,name='pdf'),
]

blogdemo/blogdemo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

class sitemaps():
    pass

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),    # 路由配置
    path(r'mdeditor/', include('mdeditor.urls'))    # 提供编辑器本地上传的功能
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 用户上传的静态文件管理，生成环境不安全

blogdemo/blog/models.py
from django.db import models
from django.urls import reverse
from mdeditor.fields import MDTextField   # markdown相关包
import markdown
# Create your models here.


class Post(models.Model):

    auth = models.ForeignKey('Auth', on_delete=models.CASCADE)

    title = models.CharField(verbose_name="标题",max_length=50)   # CharField 的 max_length 属性是必须的

    desc = models.CharField(verbose_name="简述",max_length=200,null=True,blank=True)

    pub_date = models.DateTimeField(verbose_name="发布日期")

    up_date = models.DateTimeField(verbose_name="更新日期",null=True,blank=True)

    content = MDTextField(verbose_name="内容")     # 集成文本编辑器

    tags = (("ME","杂记"),("TE","杂技"))

    tag = models.CharField(verbose_name="标签",choices=tags,max_length=10)

    visits = models.PositiveIntegerField(verbose_name="访问量",default=0)  # 访问量存储字段，初始值 0

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[str(self.id)])

    def get_tag_url(self):

        return reverse('blog:tag_post_list',args=[self.tag])

    def get_auth_url(self):

        return reverse('blog:about',args=[self.auth])

    def get_visits(self):
        self.visits = self.visits+1
        self.save(update_fields=['visits'])

        return self.visits

    def get_content_as_markdown(self):
        self.content = markdown.markdown(
        self.content,extensions = [
            # 包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            # 自动生成目录
            'markdown.extensions.toc',
			]
		)
        return self.content #markdown.markdown(self.content, safe_mode='escape')

    def get_toc(self):
        md =  markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        ])
        self.content = md.convert(self.content)
        self.toc = md.toc
        if len(self.toc)==35:

            self.toc = ""
            return self.toc

        return "<h3>目录</h3>"+self.toc

    class Meta:
        ordering = ["-pub_date"]

class Auth(models.Model):

    name = models.CharField(verbose_name='名字',max_length=50)

    about = models.TextField(verbose_name='关于',null=True,blank=False,default="暂无介绍")

    def __str__(self):

        return self.name

blogdemo/blog/views.py
from django.core.paginator import Paginator
from django.http import FileResponse, HttpResponse
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from reportlab.pdfgen import canvas

from blog.models import Post,Auth
from django.core.mail import send_mail

# Create your views here.

# 邮件发送
def sendEmail(subject,message,recipient_list):
    try:
        send_mail(
            subject = subject,                     # 标题
            message = message,                     # 正文
            recipient_list = recipient_list,       # 接收方
            from_email='2470607094@qq.com',      # 发送方
            auth_user = "2470607094@qq.com",     # 用于验证SMTP服务器的可选用户名
            auth_password = "wtbtimyrfezeeaci",  # 用于验证SMTP服务器的可选密码
            fail_silently=False,
        )
        print("success to send")
    except:
        print("fail to send")

# 首页访问次数
def visit(request):
    visits = request.session.get('visits', 1)
    request.session['visits'] = visits + 1
    # my_view(request)
    return visits

# 生成 PDF
def showPdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'

    # buffer = io.BytesIO()
    p = canvas.Canvas(response)
    p.drawString(100, 100, "Hello world.")
    p.showPage()
    p.save()
    return response

# 首页视图
def index(request):
    posts = Post.objects.all()
    # 分页操作，4 篇一页，第一个参数为 object_list 对象
    paginator = Paginator(posts, 4)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    context={
        'posts':posts,
        'visits':visit(request),
        'contacts':contacts,
    }
    return render(request, 'blog/index.html', context=context)

# 关于视图
def about(request):

    # auth = Auth.objects.get(name=name)
    #
    # print(auth)
    # context = {
    #     'auth':auth,
    # }

    return  render(request, 'blog/about.html')# ,context=context)

# 分类视图
def getTag(request,tag):
    post_list = Post.objects.filter(tag=tag)

    context = {'post_list':post_list,'tag':tag}
    return render(request, 'blog/tag_post_list.html', context)

# 文章列表视图
class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    queryset = Post.objects.all()
    context_object_name = 'post_list'

# 文章详情视图
class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'

from django.conf import settings
import os

# 上传文件视图

def upfile(request):

    return render(request, 'blog/upfile.html')


def savefile(request):

    if request.method == 'POST':
        file = request.FILES["file"]
        fpath = os.path.join(settings.MEDIA_ROOT,'user\ '+file.name)

        with open(fpath,'wb') as f:
            for info in file.chunks():
                f.write(info)
        f.close()
        return HttpResponse('<h1>上传成功</h1>')
    else:
        return HttpResponse('<h1>上传失败</h1>')

blogdemo/templates/blog/about.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}
<title>About Me</title>
    <script>
    function showimg() {
        var a = document.getElementById("img-a");
        a.innerHTML = '<br><img src="{% static 'blog/images/8.jpg' %}" >';
    }
    </script>
{% endblock %}
{% block content %}
    <br>
    <br>
<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <h1 class="display-4 font-italic">个人简介</h1>
        <p>{{ auth.name }}</p>
        <p class="lead my-3">
            大三学生，2020 年将会被消灭<br><br>
            咸鱼本人，立志做一条<strong>高盐值</strong>的咸鱼。
            会各种热门语言的 <code>Hello World!</code>
            没事喜欢写 <code>BUG</code>，然后自己改 <code>BUG</code>，让本就无聊的时光变得索然无聊。
            2020 年，努力做个 <code>Dj</code>，面对考研，适当的挣扎。<br>
        </p>
        <p class="lead mb-0">
            <a href="#" id="img-a" class="text-white font-weight-bold" onclick="showimg()">
                Learning more...
            </a>
        </p>
    </div>
</div>
{% endblock %}

blogdemo/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Hahally's BLOG</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {#设置选项卡图标#}
  <link rel="shortcut icon" href="{% static 'blog/images/favicon.ico' %}" type="image/x-icon" />
  <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
  <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="{% static 'blog/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/highlightcode.css' %}">
</head>

<body>
  <div class="container">

          <div class="col-sm-10 " >
              <div class="Hportrait" style="margin-top: 20px" align="center">
                    {#    路由解耦#}
                    <a href="{% url 'blog:about' %}">
                        <img src="{% static 'blog/images/6.jpg' %} " class="rounded-circle" >
                    </a>
              </div>
              <div>
                 <header class="blog-header py-3">
                     <div class="row flex-nowrap justify-content-between align-items-center">
                        <div class="col-4 pt-1">
                            <a class="text-muted" href="#">Subscribe</a>
                        </div>
                        <div class="col-4 text-center">
                            <p style="font-family: 华文隶书;font-size: 1.5em"><strong>I know nothing but my ignorance.</strong></p>
                            <a class="blog-header-logo text-dark" href="{% url 'blog:about' %}" style="font-family: 'Dancing Script', cursive; font-size: 1.7em;">Hahally&行走的bug</a>
                        </div>

                        <div class="col-4 d-flex justify-content-end align-items-center">
                            <a class="text-muted" href="#" aria-label="Search">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><path d="M21 21l-5.2-5.2"></path></svg>
                            </a>
                            <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
                        </div>
                    </div>
                </header>
              </div>
              <hr>
            <div class="nav-scroller py-1 mb-2">
              <nav class="nav d-flex justify-content-between">
                <a class="p-2 text-muted" href="{% url 'blog:index' %}">Home</a>
                <a class="p-2 text-muted" href="{% url 'blog:about' %}">About</a>
                <div class="dropdown">
			        <a class="btn" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				    Tags
			        </a>
			        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'blog:post_list' %}">All Blogs</a>
                        <a class="dropdown-item" href="{% url 'blog:tag_post_list' 'TE'%}">TE</a>
				        <a class="dropdown-item" href="{% url 'blog:tag_post_list' 'ME' %}">ME</a>
			        </div>
			    </div>
                <a class="p-2 text-muted" href="http://127.0.0.1:8000/admin">Admin</a>
              </nav>
            </div>
          <hr>
              {% block content %}

              {% endblock %}
          </div>
  </div>
  <div class="foot" style="margin-bottom: 0;">
      <footer class="blog-footer">
          <p>Copyright &copy; hahally</p>
          <p>
              <a href="#">Back to top</a>
          </p>
      </footer>
  </div>
</body>
</html>

blogdemo/templates/blog/index.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
    <script>
        function showimg() {
            var a = document.getElementById("img-a");
            a.innerHTML = '<br><img src="{% static 'blog/images/7.jpg' %}" >';
        }
    </script>
<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <h4 class="display-4 font-italic" style="font-size: 3.1em">Welcome to Hahally's Blog</h4>
        <p class="lead my-3">Number of visits : &nbsp;<span>{{ visits }}</span></p>
        <p class="lead mb-0"><a href="#" id="img-a" onclick="showimg()" class="text-white font-weight-bold">Continue reading...</a></p>
    </div>
</div>
<div class="row mb-2">
    {% for post in contacts %}
    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">{{ post.tag }}</strong>
          <h3 class="mb-0">{{ post.title }}</h3>
          <div class="mb-1 text-muted">{{ post.pub_date|date:'l d M Y'}}</div>
          <p class="card-text mb-auto">{{ post.desc}}</p>
          <a href="{{ post.get_absolute_url }}" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
              <title>Placeholder</title>
              <rect width="100%" height="100%" fill="#55595c"></rect>
              <text x="50%" y="50%" fill="#eceeef" dy=".3em">
              {{ post.id }}
              </text>
          </svg>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="pagination-index">
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% if contacts.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo; first</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ contacts.previous_page_number }}">previous</a>
        </li>
      {% endif %}
        {% if contacts.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ contacts.next_page_number }}">next</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ contacts.paginator.num_pages }}">last &raquo;</a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
{% endblock %}

blogdemo/templates/blog/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>

</body>
</html>

blogdemo/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block title %}
<title>{{ post.title }}</title>
{% endblock %}
{% block content %}
    <br>
    <div class="blog-post" >
        <div>
            <h2 class="blog-post-title">{{ post.title }}</h2>
            <br>
            <p>Mark：<a href="{{ post.get_tag_url }}">{{ post.tag }} </a></p>
            {#        Django 模板过滤器#}
            <p>Reading：<span>{{ post.get_visits }}</span></p>
            <p class="blog-post-meta">{{ post.pub_date|date:'D d M Y'}} By <a href="{% url 'blog:about' %}">{{ post.auth }}</a></p>
        </div>
        <div class="catalog">
            {{ post.get_toc|safe }}
        </div>
        <article>
{#            加上 safe 过滤器 防止 html 代码转义#}
            {{ post.get_content_as_markdown|safe }}
        </article>
    </div>
    <br>
    <div>
        <p><span>最近修改：{{ post.up_date }}</span></p>
    </div>
{% endblock %}

blogdemo/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block title %}
<title>All Blogs</title>
{% endblock %}
{% block content %}
    <br>
    <h1>Blog List</h1>
    <br>
    <div>
    <ul class="sidebar-nav">
    {% for post in post_list %}
        <li><a class="dropdown-item" href="{{ post.get_absolute_url }}"><span style="font-size: 1.2em">{{ post.title }}</span></a></li>
    {% endfor %}
    </ul>
    </div>
{% endblock %}

blogdemo/templates/blog/tag_post_list.html
{% extends "blog/base.html" %}
{% block title %}
<title>Blogs of {{ tag }}</title>
{% endblock %}
{% block content %}
    <br>
    <h1>Blog List</h1>
    <br>
    <div>
    {% if post_list %}
    <ul class="sidebar-nav">
    {% for post in post_list %}
        <li ><a class="dropdown-item" href="{{ post.get_absolute_url }}" >{{ post.title }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p><span>暂时没有！</span></p>
    {% endif %}
    </div>
{% endblock %}

blogdemo/templates/blog/upfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文件上传</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data" action="{% url 'savefile' %}">
        {% csrf_token %}
        <input type="file" name="file">
        <input type="submit">
    </form>
</body>
</html>